name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.2]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          # sudo apt-get install libicu-dev pkg-config
          poetry install  # --no-dev
          # poetry add pyicu pycld2
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: poetry run pytest tests
