name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.2]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          # pip config set global.disable-pip-version-check true
          # sudo apt-get install libicu-dev pkg-config
          poetry run pip install whl\PyICU-2.8.1-cp38-cp38-win_amd64.whl
          poetry run pip install whl\pycld2-0.41-cp38-cp38-win_amd64.whl
          poetry run pip install git+https://github.com/aboSamoor/polyglot@master
          poetry install  # --no-dev
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: poetry run pytest tests
